version: '2'

services:
  master:
    image: centos_ssh
    ports:
      - "22"
      - "50070"
      - "8088"
      - "19888"

  slave:
    image: centos_ssh
    ports:
      - "22"

  hive:
    image: centos_ssh
    ports:
      - "22"
