machine_1:
  build: centos_ssh/.
  ports:
    - "22"
machine_2:
  build: centos_ssh/.
  ports:
    - "22"
machine_3:
  build: centos_ssh/.
  ports:
    - "22"
machine_4:
  build: centos_ssh/.
  ports:
    - "22"
