---
# Gather facts to be able to use them in next plays
- hosts: all
  gather_facts: yes
  remote_user: deploy

- hosts: all
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: etc_hosts, machines: all, tags: [etc, zookeeper, graphite, grafana, kafka, client] }

- hosts: zoo_keeper
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: jdk, tags: [zookeeper] }
    - { role: zookeeper/install, tags: [zookeeper] }
    - { role: zookeeper/server, tags: [zookeeper] }

- hosts: graphite
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: graphite, tags: [graphite] }

- hosts: grafana
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: grafana, tags: [grafana] }

- hosts: kafka
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: jdk, tags: [kafka] }
    - { role: kafka/install, tags: [kafka] }
    - { role: kafka/server, tags: [kafka] }

- hosts: client
  gather_facts: no
  remote_user: deploy
  roles:
    - { role: jdk, tags: [client] }
    - { role: kafka/install, tags: [client] }
    - { role: kafka/connect, tags: [client, connect] }
